project:
  type: website
  output-dir: docs

website:
  title: "JIE-2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    #css: styles.css
    toc: true
    theme: minty
    #light: quartz
    #dark: vapor