project:
  type: website
  output-dir: docs

website:
  announcement: 
    icon: info-circle
    content: "**Programa actualizado!!!**" 
    position: below-navbar 
  title: "JIE-2024"
  back-to-top-navigation: true
  navbar:
    search: true
    left:
      - icon: house
        href: index.qmd
        text: Home
      #- about.qmd
    right:
        - text: Inscripciones
          menu:
            - text: Envío de trabajos
              href: https://forms.gle/Wfqnd3auRDXCiCtC8
              target: _blank
            - text: Inscripción como asistente
              href: https://www.google.cl/?hl=es
              target: _blank
        - href: program/index.qmd
          text: Programa          
        - text: Eventos anteriores
          menu:
            - text: JIE-2023
              href: index.qmd
            - text: JIE-2022
              href: index.qmd
  page-footer:  
    border: true
    background: dark
    center:
      - icon: envelope
        href: mailto:jornadas.estadistica.dmcc@usach.cl
        text: Contáctanos a jornadas.estadistica.dmcc@usach.cl
      - text: >- 
          <br> &#169; 2024 Jornadas Ingeniería Estadística USACH <br> Hecho con [Quarto](https://quarto.org)
       
format:
  html:
    css: custom_light.scss
    toc: false
    theme: 
      - minty
      - custom_light.scss
        #light: [minty, custom_light.scss]
        #dark: [minty, custom_dark.scss]

# include CSS style for title blocks
include-in-header:
  - text: |
      <style>
      .quarto-title-block .quarto-title-banner {
        flex-direction: row;
        display: flex;
        justify-content: flex-start; /* Cambiado para alinear el logo con el texto */
        align-items: center;
        height: 350px;
        z-index: 2;
        padding: 0;
        background-image: url(images/logos_usach.png);
        background-repeat: no-repeat;
        background-position: top;
        background-size: 350px 60px;
      }
      .quarto-title-block .quarto-title-banner::before {
        content: '';
        background-image: url(images/JIE_logo.png);
        background-repeat: no-repeat;
        background-position: left; /* Cambiado para que el logo esté más cerca del texto */
        background-size: 250px 250px;
        width: 250px;
        height: 250px;
        margin-right: 30px; /* Ajuste para alinear con el texto */
      }
      .quarto-title-block .quarto-title-banner h1.title {
        margin: 0;
        text-align: left;
        font-size: 2.5em;
      }
      </style>