project:
  type: website
  output-dir: docs

website:
  title: "JIE-2024"
  navbar:
    search: true
    left:
      - icon: house
        href: index.qmd
        text: Home
      #- about.qmd
    right: 
        - href: index.qmd
          text: Envío de trabajos
        - href: index.qmd
          text: Programa          
        - text: Eventos anteriores
          menu:
            - text: JIE-2023
              href: index.qmd
            - text: JIE-2022
              href: index.qmd

format:
  html:
    #css: styles.css
    toc: true
    theme: #minty
        light: minty
        dark: [minty, custom_dark.css]
 
 # include CSS style for title blocks
title-block-banner: "#00000000"
title-block-banner-color: "rgba(255, 255, 255, 0.9)"
include-in-header:
  - text: |
      <style>
      #title-block-header.quarto-title-block.default .quarto-title-meta {
        color: rgba(255, 255, 255, 0.9);
      }
      .quarto-title-block .quarto-title-banner {
        height: 0; /* hide */
      }
      #title-block-header {
        background: 
          /* top, transparent black, faked with gradient */
          linear-gradient(
            rgba(0, 0, 0, 0.7),
            rgba(0, 0, 0, 0.7)
          ),
          /* bottom, image */ 
          url(images/banner_jornadas.png);
        background-size: cover;
        background-position-y: center;
        height: 300px;
        opacity: 0.7; /* image opacity, lower means lighter */
        z-index: -1;
      }
      </style>