project:
  type: website

website:
  title: "today"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    css: styles.css
    toc: true
    light: quartz
    dark: vapor