project:
  type: website
  output-dir: docs

website:
  title: "JIE-2024"
  navbar:
    search: true
    left:
      - icon: house
        href: index.qmd
        text: Home
      #- about.qmd
    right: 
        - href: index.qmd
          text: Envío de trabajos
        - href: index.qmd
          text: Programa          
        - href: index.qmd
          text: Eventos anteriores

format:
  html:
    #css: styles.css
    toc: true
    theme: #minty
        light: minty
        dark: [minty, custom_dark.css]