project:
  type: website
  output-dir: docs

website:
  title: "JIE-2024"
  navbar:
    search: true
    left:
      - icon: house
        href: index.qmd
        text: Home
      #- about.qmd
    right: 
        - href: https://forms.gle/Wfqnd3auRDXCiCtC8
          text: Envío de trabajos
          target: _blank
        - href: index.qmd
          text: Programa          
        - text: Eventos anteriores
          menu:
            - text: JIE-2023
              href: index.qmd
            - text: JIE-2022
              href: index.qmd

format:
  html:
    #css: styles.css
    toc: false
    theme: #minty
        light: [minty, custom_light.css]
        dark: [minty, custom_dark.css]

# include CSS style for title blocks
include-in-header:
  - text: |
      <style>
      .quarto-title-block .quarto-title-banner {
        flex-direction: row;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 400px;
        z-index: 2;
        padding: 0 ;
        background-image: url(images/logos_usach.png);
        background-repeat: no-repeat;
        background-position: top;
        background-size: 400px 70px;;
        }
       .quarto-title-block .quarto-title-banner::before {
        content: '';
        background-image: url(images/JIE_logo.png);
        background-repeat: no-repeat;
        background-position: center;
        background-size: contain;
        width: 250px;
        height: 250px;
        margin-right: 20px;
      }
      .quarto-title-block .quarto-title-banner h1.title {
        margin: 0;
        text-align: left;
        font-size: 2.5em;
      }
      </style>