---
title: "III Jornadas Ingeniería Estadística"
subtitle: "11 al 12 de Noviembre 2024 <br> Auditorio Departamento de Matemática y Ciencia de la Computación <br> Universidad de Santiago de Chile"
title-block-banner: "#d394f8"
lang: es
format: 
  html:
    embed-resources: true
---

## ¡Programa actualizado 2

Hemos actualizado el [programa](program/index.qmd) para **incorporar más presentaciones**, dada la **alta convocatoria** que hemos recibido. ¡Gracias por el entusiasmo!

### **Modalidades de participación**

La participación en las Jornadas puede ser como:  
- **Presentador:** Formato oral (presentación corta) o póster.  
- **Asistente:** ¡Cupos limitados! Los invitamos a inscribirse pronto para asegurar su participación.

**[Formulario de inscripción para asistentes](https://docs.google.com/forms/d/e/1FAIpQLSfXoiOwlAV2eItd1HpnO7iGLXChLn0SeKph17k1Y9SmF1NxxQ/viewform){target="_blank"}**

::: {.columns}
::: {.column width="45%"}
### Participación como Presentador

Los interesados en presentar pueden enviar sus trabajos para ser considerados en formato oral o póster en las **3ras Jornadas de Ingeniería Estadística de la USACH**.
:::
::: {.column width="55%"}
| **Fecha Límite de envío de resúmenes:** 14 de Octubre | 
|:----------------------------------------------------:|
| [Formulario de inscripción de trabajos](https://forms.gle/Wfqnd3auRDXCiCtC8){target="_blank"} |
:::
:::

**¡Consulta el [programa completo](program/index.qmd)!** No te pierdas ninguna de las actividades y asegúrate de inscribirte a tiempo para participar.
