---
title: "Programa"
#subtitle: "11 al 12 de Noviembre 2024"
#description: "Auditorio Departamento de Matemática y Ciencia de la Computación"
title-block-banner: "#d394f8"
lang: es
format: 
  html:
    embed-resources: true
---

| Hora              | Lunes 11 de noviembre                        | Martes 12 de noviembre                            |
|:----------------- |:--------------------------------------------|:-------------------------------------------------|
| 09:35 - 09:50     | **Bienvenida-Inauguración**                 |                                                  |
| 09:50 - 10:30     | Soledad Torres Díaz <br> *(Universidad Central)*  | Felipe Barrientos <br> *(Florida State University, EEUU)* |
| 10:30 - 11:10     | Héctor Araya Carvajal <br> *(Universidad Adolfo Ibáñez)* | Claudia Chavez <br> *(Investigadora FLACSO)* |
| 11:10 - 11:30     | **Coffee Break**                            | **Coffee Break**                                 |
| 11:30 - 12:00     | Mini curso *Quarto - Github* <br> Francisco Plaza-Vega | Mini curso *Quarto - Github* <br> Francisco Plaza-Vega |
| 12:00 - 13:20     | **Sesiones Orales**                         | **Sesiones Orales**                              |
|                   | [Partial identification in ILSA studies of educational achievement: A strategy for producing credible interval estimates with student non-participation](../abstracts/index.qmd#partial-identification-in-ilsa-studies-of-educational-achievement-a-strategy-for-producing-credible-interval-estimates-with-student-non-participation) <br> **Maximiliano Romero** (Afiliación pendiente) | [Predicción de Desembarcos de Pulpo (*Octopus vulgaris*) con Inteligencia Artificial: Una Demo Interactiva en R](../abstracts/index.qmd#predicci%C3%B3n-de-desembarcos-de-pulpo-octopus-vulgaris-con-inteligencia-artificial-una-demo-interactiva-en-r) <br> **Victor Sanz-Fernández** (PUCV) |
|                   | [Factores asociados en el rendimiento de pruebas Simce: propuesta de análisis inferencial y hallazgos](../abstracts/index.qmd#factores-asociados-en-el-rendimiento-de-pruebas-simce-propuesta-de-an%C3%A1lisis-inferencial-y-hallazgos) <br> **Esteban Avarca Oviedo** (USACH) | [Análisis de factores de reincidencia delictual en Chile utilizando Machine Learning y Técnicas de Agrupamiento](../abstracts/index.qmd#an%C3%A1lisis-de-factores-de-reincidencia-delictual-en-chile-utilizando-machine-learning-y-t%C3%A9cnicas-de-agrupamiento) <br> **Vicente Jopia Alburquenque** (USACH) |
|                   | [Modelo BNP para datos discretos con aplicación al rendimiento de clubes deportivos](../abstracts/index.qmd#modelo-bnp-para-datos-discretos-con-aplicaci%C3%B3n-al-rendimiento-de-clubes-deportivos) <br> **Cristian Capetillo Constela** (PUC) | [El uso de los modelos de distribución de especies para la construcción de distribuciones a priori en inferencia bayesiana](../abstracts/index.qmd#el-uso-de-los-modelos-de-distribuci%C3%B3n-de-especies-para-la-construcci%C3%B3n-de-distribuciones-a-priori-en-inferencia-bayesiana) <br> **Mateo Antonio Morales Herrera** (UChile) |
|                   | [Weibull random fields through Clayton spatial copula: an application to mining haul roads](../abstracts/index.qmd#weibull-random-fields-through-clayton-spatial-copula-an-application-to-mining-haul-roads) <br> **Eloy Alvarado Narváez** (UTFSM) | [Estimación de Parámetros mediante Simulación-Extrapolación en Procesos Autorregresivos cercanos a la Raíz Unitaria](../abstracts/index.qmd#estimaci%C3%B3n-de-par%C3%A1metros-mediante-simulaci%C3%B3n-extrapolaci%C3%B3n-en-procesos-autorregresivos-cercanos-a-la-ra%C3%ADz-unitaria) <br> **Pablo Vicari Ruiz** (USACH) |
| 13:20 - 14:00     | **Coffee Break - Posters**                  | **Coffee Break - Posters**                       |
